# version: '3.9'

services:
  client:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true" 
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - server
  server:
    build: ./server
    environment:
      PORT: 4000
      CHOKIDAR_USEPOLLING: "true"
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "4000:4000"
    volumes:
      - ./server:/server
      - /server/node_modules      
    depends_on:
      - db
          
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data      
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: perfume

volumes:
  postgres_data: